### ISSUE TITLE
重复号码BUG

### ISSUE THREAD

**Issue by liesauer** [kuyermqi/scratch-off#2]
没玩过刮刮乐，但是这种情况应该是BUG吧？

![image](https://github.com/kuyermqi/scratch-off/assets/8676741/c3c9faaf-e3d1-49ea-889f-e02c7abbb8df)

**Comment by 657kbps** [comment]
这个玩具性质的项目使用的随机数生成方法并不严谨~但我并不打算花更多的时间继续更新这个项目，如果有需要可以自己 fork `并修改下面这个函数：
https://github.com/kuyermqi/scratch-off/blob/79382fe25978f60ddc342ae8a4711c612fb69794/src/App.jsx#L8C1-L21
